### ISSUE TITLE
Output limitation

### ISSUE THREAD

**Issue by heaks** [comerc/meteor-autoform-typeahead#19]
Is there any way to limit the output (let's say to 5) ?
I have this code:
**HTML**
`{{> afQuickField name=current.name class="form-control" type="typeahead"}}`

**CoffeeScript** Simple shema

```
  ingredients:
    type: [Object]
    optional: true
  'ingredients.$.name':
    type: String
    label: 'ingredient'
    autoform:
      options: ->
        Ingredients.find({}).fetch().map((it) -> {label: it.name})
```

It works, but when I type, for example, 'a' in input field, it gives me too many results, I need to limit them to 5 or so.
